# Generated by Django 4.2.7 on 2023-12-01 11:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="compra",
            name="tipo_pagamento",
            field=models.IntegerField(
                choices=[
                    (1, "Cartão de Crédito"),
                    (2, "Cartão de Débito"),
                    (3, "PIX"),
                    (4, "Boleto"),
                    (5, "Transferência Bancária"),
                    (6, "Dinheiro"),
                    (7, "Outro"),
                ],
                default=1,
            ),
        ),
    ]
