# Generated by Django 4.2.7 on 2023-12-07 17:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_compra_tipo_pagamento"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="produto",
            name="tamanho",
        ),
        migrations.AddField(
            model_name="produto",
            name="tamanho",
            field=models.ManyToManyField(related_name="itens", to="core.tamanho"),
        ),
    ]
