# Generated by Django 4.2.7 on 2023-12-07 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_remove_produto_tamanho_produto_tamanho"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="produto",
            name="tamanho",
        ),
        migrations.AddField(
            model_name="produto",
            name="tamanho",
            field=models.ForeignKey(
                default=2, on_delete=django.db.models.deletion.PROTECT, related_name="itens", to="core.tamanho"
            ),
            preserve_default=False,
        ),
    ]
