# Generated by Django 4.2.7 on 2023-12-01 11:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usuario", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="tipo_usuario",
            field=models.IntegerField(choices=[(1, "Cliente"), (2, "Admin")], default=1, verbose_name="User Type"),
        ),
    ]
