# Generated by Django 4.2.7 on 2023-12-07 20:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usuario", "0004_usuario_foto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="data_nascimento",
            field=models.DateField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="A data deve estar no formado Dia-Mês-Ano", regex="%d-%m-%Y"
                    )
                ],
                verbose_name="Birth Date",
            ),
        ),
    ]
