# Generated by Django 4.2.7 on 2023-12-07 22:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usuario", "0006_alter_usuario_data_nascimento"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="data_nascimento",
            field=models.DateField(blank=True, null=True, verbose_name="Birth Date"),
        ),
    ]
